import type { IconsGeneratorParams } from '@mevbg/design-essentials-vendor';

export const icons: IconsGeneratorParams = {
  fontFamily: 'Iconography', // optional (Iconography by default)
  color: 'var(--mev-color-content-gray-weak)', // optional (currentColor by default)
  list: {
    main:              'E000',
    nav:               'E001',
    search:            'E002',
    profile:           'E003',
    play:              'E004',
    publication:       'E005',
    close:             'E006',
    clear:             'E007',
    arrowRight:        'E008',
    arrowDown:         'E009',
    arrowUp:           'E00A',
    slideLeftSmall:    'E00B',
    slideRightSmall:   'E00C',
    slideLeftMiddle:   'E00D',
    slideRightMiddle:  'E00E',
    slideLeftBig:      'E00F',

    slideRightBig:     'E010',
    maximize:          'E011',
    minimize:          'E012',
    star:              'E013',
    today:             'E014',
    liveNews:          'E015',
    leadingNews:       'E016',
    show:              'E017',
    hide:              'E018',
    camera:            'E019',
    check:             'E01A',
    dropdownArrow:     'E01B',
    threeDots:         'E01C',
    thumbsUp:          'E01D',
    thumbsDown:        'E01E',
    ban:               'E01F',

    social:            'E100',
    facebook:          'E101',
    x:                 'E102',
    viber:             'E103',
    email:             'E104',
    rss:               'E105',
    telegram:          'E106',
    linkedin:          'E107',
    link:              'E108',
    print:             'E109',
    heart:             'E10A',
    googleMark:        'E10B',
    facebookMark:      'E10C',
    appleMark:         'E10D',
    logo:              'E10E',
    home:              'E10F',

    heartFilled:       'E020',
    thumbsUpFilled:    'E021',
    thumbsDownFilled:  'E022',
    readings:          'E023',
    comments:          'E024',
    thumbsUp2:         'E025',
    thumbsDown2:       'E026',
    thumbsUp2Filled:   'E027',
    thumbsDown2Filled: 'E028',
    bookmark:          'E029',
    bookmarkFilled:    'E02A',

    plus:              'E110',
    weather:           'E200',

    astrology:         'E300',
    capricorn:         'E301',
    aquarius:          'E302',
    pisces:            'E303',
    aries:             'E304',
    taurus:            'E305',
    gemini:            'E306',
    cancer:            'E307',
    leo:               'E308',
    virgo:             'E309',
    libra:             'E30A',
    scorpio:           'E30B',
    sagittarius:       'E30C',
  }
};
